version: '2'
services:
  web:
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    # ports from container exposed to the docker machine and the guest machine
    ports:
      # 80 on the host, 8080 on the guest. Websever listens on 8080
      - "8080:8080"
    # file with environment declarations for the container
    env_file:
      - .env
    # Link to containers in another service
    depends_on:
      - db
    # sync workspace folder with /go
    volumes:
      - ../../../../.:/go
  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    ports:
      - "3306:3306"
    environment:
      - "MYSQL_DATABASE=gourlshort"
      - "MYSQL_USER=docker"
      - "MYSQL_PASSWORD=docker"
      - "MYSQL_ROOT_PASSWORD=root"
